### ISSUE TITLE
CSS3 :not() selector problem

### ISSUE THREAD

**Issue by qazbnm456** [keicheng/kule.lazy#12]
I found that there is a problem in [kule-lazy.min.css](https://github.com/keicheng/kule.lazy/blob/master/dist/css/kule-lazy.min.css).

This ".info-item:not('.hide')" is expected to be ".info-item:not(.hide)", right? Thanks for doing such a great CSS Framework by the way.

**Comment by keicheng** [comment]
Thanks, i`ll fix it

**Comment by keicheng** [comment]
fixed
