### ISSUE TITLE
[DOCS] 換頁時每個元件都會有動畫縮放效果導致 Lag

### ISSUE THREAD

**Issue by YamiOdymel** [keicheng/kule.lazy#14]
![untitled](https://cloud.githubusercontent.com/assets/7308718/24044191/40e3a312-0b55-11e7-8eee-307c26754c80.gif)

不太清楚這是特效，還是有可能元件裡面有類似 `transition all 0.5s ease` 之類的效果所導致的問題，但網頁在 Macbook Air 13" 2013 上面瀏覽有點卡頓。

瀏覽器是 Chrome 57。
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
```

**Comment by keicheng** [comment]
抱歉，最近都沒上來看，
感謝告知，處理中。
