### ISSUE TITLE
[issue] 本機直接讀取檔案錯誤資訊

### ISSUE THREAD

**Issue by twbcs** [keicheng/kule.lazy#6]
OS: MAC OSX 10.11
Device: Desktop
Browser: Chrome 46.0.2490.80 (64-bit)
issue:  本機下直接開網頁 會在載入階段無窮迴圈...無法載入網頁
Failed to get text for stylesheet 37855.6: No style sheet with given id found
javascript console 的錯誤訊息 不停重複

Browser: Safari 9.0.1
issue:  本機下直接開網頁 
kule.jquery-ui.min.css 會跳警告
-ms-filter: progid: DXImageTransform.Microsoft.Alpha(opacity=50);

以上錯誤 將檔案上傳伺服器後 讀取時都無錯誤產生

載入檔案為
  <link rel="stylesheet" href="css/kule-lazy-full-ie.min.css" />
  <link rel="stylesheet" href="css/kule-animates.min.css" />
  <link rel="stylesheet" href="css/kule-effects.min.css" />
  <link rel="stylesheet" href="css/kule-jquery-ui.min.css" />
  <script type="text/javascript" src="js/kule.urbrowser.min.js"></script>
  <script type="text/javascript" src="js/jquery-1.11.1.min.js" charset="utf-8"></script>

另外 選單在縮小畫面後 選單點擊圖示無反應 文件那內容大抵上就是官網NAV內容（desktop,mobile 都是同狀況）

PS.版本應該是最新版 剛剛從官網下載的

**Comment by keicheng** [comment]
在本機的時候，網址是 file:/// 開頭嗎？
如果是的話，有兩個方法可以解決無窮迴圈載入的問題
1. 使用 `http://localhost` 或是 `http://127.0.0.1`
2. 請下載最新版本的 [urBrowser 2.151103](http://urbrowser.kule.tw) (剛剛緊急修正)

你的第二個問題
在 safari 下對於 -ms-filter 會產生警告，-ms-是給IE使用，所以不會造成 safari 的錯誤

最後一個問題在 [Facebook](https://www.facebook.com/kule.tw/posts/1068082569869996) 上有跟大家報告，實際上 Kule Lazy 目前沒有提供任何 js 的部分，如果你需要 nav 的 toggle 效果，js如下：

``` html
$(document).ready(function() {
    $('.navbar-toggle').on('click', function() {
        var that = $(this);
        var wrap = that.parents('.navbar');
        var target = wrap.find('.navbar-content');

        that.toggleClass('active');
        target.toggleClass('open');
    });
});
```

**Comment by twbcs** [comment]
謝謝！！

**Comment by keicheng** [comment]
如有發現其他問題歡迎提問
