### ISSUE TITLE
關於navbar position fixed 

### ISSUE THREAD

**Issue by twbcs** [keicheng/kule.lazy#7]
抱歉 請問 navbar 要如何固定在螢幕上方
因為我 css使用 .navbar {position: fixed} 會縮成一小區塊 而不是原本的橫槓.

**Comment by wusinhan** [comment]
再加上一個 width: 100%; 試看看。

**Comment by twbcs** [comment]
可以了 謝謝

**Comment by keicheng** [comment]
thanks
